services:
  - type: web
    name: void-editor
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci --legacy-peer-deps --ignore-scripts && npm run compile-web && npm run download-builtin-extensions
    startCommand: node server.js
    healthCheckPath: /
    dockerfilePath: ""
    skipAutoDetect: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: npm_config_user_agent
        value: npm
      - key: VSCODE_SKIP_YARN_CHECK
        value: "1"
      - key: npm_execpath
        value: /usr/bin/npm

